services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: animalia_user
      POSTGRES_PASSWORD: animalia_password
      POSTGRES_DB: animalia_database
