services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - animalia_database:/var/lib/postgresql/data

volumes:
  animalia_database:
